name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      #- name: start containers
      #  run: 

      # use this step to give time for containers to start
      - name: wait for containers to be ready
        run: sleep 5s
        shell: bash

      #- name: run tests on the api
      #  run: 

      # you also need to run tests on the client